### ISSUE TITLE
Installation suggestions

### ISSUE THREAD

**Issue by Plavit** [arras-energy/gridlabd#22]
## Background
I was installing GridLAB-D in the past few days for a research project and it proved unnecessarily complex, I propose a few changes to Readme that will solve this issue.

## Proposed solution
Three changes proposed to README.md for better clarity:

1. Remove the **Contributions** section, as https://source.gridlabd.us/blob/master/CONTRIBUTING.md does not exist.

2. Add the following to the **Windows WSL** section:
GridLAB-D supports several WSL distributions, including the latest Ubuntu versions. See the setup folder for currently supported distributions.

3. Add the following to the **Windows WSL** section below the validation code `./build.sh --system --validate` :
The validation may take some time and it need not complete completely successfully for GridLAB-D to be used. The final report may look something like this:

```
Validation report:
747 models tested
1 unexpected errors
746 tests succeeded
>99% success rate
Total validation elapsed time: 281.9 seconds
See '/home/username/gridlabd/validate.txt' for details
ERROR [build.sh]: unable to verify install 
```

## Alternatives
Feel free to amend my proposed wording

## Additional context
Not needed

**Comment by dchassin** [comment]
@plavit, do you plan to submit your source code changes at some point?  If so, please note that we had to rebuild the original `arras-energy/gridlabd` repo from scratch due to problems with old DCOs.  The original repo is renamed `gridlabd-old` and the new one is now called `gridlabd`.  Consequently, you may need to fork the new one to get updates and submit contributions.

**Comment by Plavit** [comment]
Okay, we'll look into it, thanks for highlighting!
